In [ ]:
#BOW 직접구현

In [23]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
       '오늘 동물원에서 원숭이게 사과를 줬어']

In [24]:
docs

['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어', '오늘 동물원에서 원숭이게 사과를 줬어']

In [25]:
#띄어쓰기 토큰화
doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split(' '))
print(doc_ls)

#빈 딕셔너리 만들기
from collections import defaultdict
word2id = defaultdict(lambda:len(word2id))

#중복이 되는 토큰은 한번씩만 들어가게 된다.
for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'], ['오늘', '동물원에서', '원숭이게', '사과를', '줬어']]


defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '코끼리': 2,
             '원숭이를': 3,
             '보고': 4,
             '원숭이에게': 5,
             '먹이를': 6,
             '줬어': 7,
             '원숭이게': 8,
             '사과를': 9})

In [26]:
import numpy as np
Bow_ls=[]
for i, doc in enumerate(doc_ls):
    bow=np.zeros(len(word2id),dtype=int)
    print(bow)
    for token in doc:
        bow[word2id[token]] +=1 #해당토큰위치(column)
    Bow_ls.append(bow.tolist())
#1차원 배열
Bow_ls

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1, 1, 0, 0], [1, 1, 0, 0, 0, 0, 0, 1, 1, 1]]

In [27]:
from IPython.core import display as ICD
import pandas as pd
sorted_vocab=sorted((value,key) for key, value in word2id.items())
print('sorted_vocab',sorted_vocab)

sorted_vocab [(0, '오늘'), (1, '동물원에서'), (2, '코끼리'), (3, '원숭이를'), (4, '보고'), (5, '원숭이에게'), (6, '먹이를'), (7, '줬어'), (8, '원숭이게'), (9, '사과를')]


In [29]:
vocab=[]
for v in sorted_vocab:
    vocab.append(v[1])
print('vocab',vocab)
for i in range(len(docs)):
    print("문서{} : {}".format(i,docs[i]))
    ICD.display(pd.DataFrame([Bow_ls[i]],columns=vocab))
    print("\n\n")

vocab ['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '원숭이에게', '먹이를', '줬어', '원숭이게', '사과를']
문서0 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  원숭이게  사과를
0   1      1    2     1   1      1    1   1     0    0




문서1 : 오늘 동물원에서 원숭이게 사과를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  원숭이게  사과를
0   1      1    0     0   0      0    0   1     1    1

In [ ]:
#단어의 순서를 고려하지 않은 BOW

In [30]:
docs=['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해',
     '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']

In [31]:
docs

['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해', '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']

In [32]:
doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split())
doc_ls    

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

In [33]:
#빈 딕셔너리 만들기
from collections import defaultdict
word2id = defaultdict(lambda:len(word2id))

#중복이 되는 토큰은 한번씩만 들어가게 된다.
for doc in doc_ls:
    for token in doc:
        word2id[token]
word2id

defaultdict(<function __main__.<lambda>()>,
            {'나는': 0,
             '양념': 1,
             '치킨을': 2,
             '좋아해': 3,
             '하지만': 4,
             '후라이드': 5,
             '싫어해': 6})

In [34]:
import numpy as np
Bow_ls=[]
for i, doc in enumerate(doc_ls):
    bow=np.zeros(len(word2id),dtype=int)
    print(bow)
    for token in doc:
        bow[word2id[token]] +=1 #해당토큰위치(column)
    Bow_ls.append(bow.tolist())
#1차원 배열
Bow_ls

[0 0 0 0 0 0 0]
[0 0 0 0 0 0 0]


[[1, 1, 2, 1, 1, 1, 1], [1, 1, 2, 1, 1, 1, 1]]

In [35]:
from IPython.core import display as ICD
import pandas as pd
sorted_vocab=sorted((value,key) for key, value in word2id.items())
print('sorted_vocab',sorted_vocab)

sorted_vocab [(0, '나는'), (1, '양념'), (2, '치킨을'), (3, '좋아해'), (4, '하지만'), (5, '후라이드'), (6, '싫어해')]


In [36]:
vocab=[]
for v in sorted_vocab:
    vocab.append(v[1])
print('vocab',vocab)
for i in range(len(docs)):
    print("문서{} : {}".format(i,docs[i]))
    ICD.display(pd.DataFrame([Bow_ls[i]],columns=vocab))
    print("\n\n")

vocab ['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '싫어해']
문서0 : 나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1




문서1 : 나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해


나는  양념  치킨을  좋아해  하지만  후라이드  싫어해
0   1   1    2    1    1     1    1

In [ ]:
##SKLEARN

In [55]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
       '오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어']

In [56]:
#토큰 빈도계산 : CounterVectorizer
from sklearn.feature_extraction.text import CountVectorizer
#선언
count_vect=CountVectorizer()
BoW=count_vect.fit_transform(docs)
print(BoW.toarray())

[[1 1 1 0 1 1 1 1 2]
 [2 1 1 1 2 1 2 2 2]]


In [57]:
vocab=count_vect.get_feature_names()
print(vocab)

['동물원에서', '먹이를', '보고', '사과를', '오늘', '원숭이를', '원숭이에게', '줬어', '코끼리']


In [59]:
import pandas as pd

for i in range(len(docs)):
    print("문서{} : {}".format(i,docs[i]))
    print('\n')
    df=pd.DataFrame([BoW.toarray()[i]],columns=vocab)
    print(df)
    print("\n\n")

문서0 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


   동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      1    1   1    0   1     1      1   1    2



문서1 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어


   동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      2    1   1    1   2     1      2   2    2





In [47]:
###gensim
!pip install gensim

  Created wheel for smart-open: filename=smart_open-2.1.1-py3-none-any.whl size=112418 sha256=dc4c45e9a8617fa9f9ed7eb709e1332eb9843b84d7986ce8689b48ff8b796b77
  Stored in directory: c:\users\kang9\appdata\local\pip\cache\wheels\07\d8\70\da31eb9ec5ff49ac74f1a5944704029f0b6fd74fdf318ec300
Successfully built smart-open


In [60]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
       '오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어']

In [61]:
from gensim import corpora

#토큰화시키기
doc_ls=[]
for doc in docs:
    doc_ls.append(doc.split())
print(doc_ls)    
id2word=corpora.Dictionary(doc_ls)
print('----')
#토큰화한이후 유니크한 것만 들어간다
print(id2word)

BoW=[]
for doc in doc_ls:
    BoW.append(id2word.doc2bow(doc))
BoW   

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'], ['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어', '오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]
----
Dictionary(9 unique tokens: ['동물원에서', '먹이를', '보고', '오늘', '원숭이를']...)


[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 2)],
 [(0, 2), (1, 1), (2, 1), (3, 2), (4, 1), (5, 2), (6, 2), (7, 2), (8, 1)]]

In [62]:
BoW [0]

[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 2)]

In [63]:
from gensim.matutils import sparse2full
from IPython.core import display as ICD
import pandas as pd
vocab=[id2word[i] for i in id2word.keys()]
for i in range(len(docs)):
    print("문서{} : {}".format(i,docs[i]))
    ICD.display(pd.DataFrame([sparse2full(BoW[i],len(vocab))],columns=vocab))
    print("\n\n")

문서0 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


동물원에서  먹이를   보고   오늘  원숭이를  원숭이에게   줬어  코끼리  사과를
0    1.0  1.0  1.0  1.0   1.0    1.0  1.0  2.0  0.0




문서1 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어


동물원에서  먹이를   보고   오늘  원숭이를  원숭이에게   줬어  코끼리  사과를
0    2.0  1.0  1.0  2.0   1.0    2.0  2.0  2.0  1.0