In [4]:
#인코딩 대상 단어를 담은 리스트
word_ls=['원숭이','바나나','사과','코끼리']

In [7]:
from collections import defaultdict
import numpy as np
#{단어 : 인덱스} 사전구축
word2id_dic = defaultdict(lambda:len(word2id_dic))
word2id_dic

defaultdict(<function __main__.<lambda>()>, {})

In [8]:
for word in word_ls:
    word2id_dic[word]
word2id_dic    

defaultdict(<function __main__.<lambda>()>,
            {'원숭이': 0, '바나나': 1, '사과': 2, '코끼리': 3})

In [9]:
#고유한 단어 갯수
n_unique_words=len(word2id_dic)
n_unique_words

4

In [11]:
#원핫 백터를 만들기 위해 비어있는 벡터를 생성
one_hot_vectors = np.zeros((len(word_ls),n_unique_words))
one_hot_vectors  

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
#단어고유 인덱스
for i,word in enumerate(word_ls):
    index=word2id_dic[word]
    one_hot_vectors[i,index]+=1  #단어 고유 인덱스에 1을 더해줌
one_hot_vectors

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
##sklearn

In [19]:
word_ls

['원숭이', '바나나', '사과', '코끼리']

In [16]:
pip install sklearn

  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1321 sha256=140657d5682ab6da47998e84b6ca33a8291f42117df942730edb9fdb6e279091
  Stored in directory: c:\users\kang9\appdata\local\pip\cache\wheels\23\9d\42\5ec745cbbb17517000a53cecc49d6a865450d1f5cb16dc8a9c
Successfully built sklearn



In [20]:
#sklearn을 활용한 one-hot encoding
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [26]:
#예제 데이터 배열
values=array(word_ls)
values

array(['원숭이', '바나나', '사과', '코끼리'], dtype='<U3')

In [27]:
# 문자열에 숫자를 붙임
label_enc=LabelEncoder() #선언
int_enc=label_enc.fit_transform(values)
int_enc

array([2, 0, 1, 3], dtype=int64)

In [28]:
#binary encode
onehot_enc=OneHotEncoder(sparse=False) #선언 #false로 하면 결과값이 배열로 나온대
int_enc=int_enc.reshape((len(int_enc),1)) #n:1 matrix로 변화
onehot_enc=onehot_enc.fit_transform(int_enc)
onehot_enc

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])